---
- name: php_install | Add external repository for PHP by using geerlingguy role
  ansible.builtin.import_role:
    name: geerlingguy.php-versions
  vars:
    php_version: "{{ php_ver }}"
  when: php_install_external_repos

- name: php_install | Install required PHP packages for Nextcloud
  ansible.builtin.package:
    name:
      - imagemagick
      - smbclient
      - "php{{ php_ver }}-fpm"
      - "php{{ php_ver }}-gd"
      - "php{{ php_ver }}-ldap"
      - "php{{ php_ver }}-imap"
      - "php{{ php_ver }}-curl"
      - "php{{ php_ver }}-intl"
      - "php{{ php_ver }}-bz2"
    state: present
  notify:
    - Start php-fpm

- name: php_install | Install extra packages
  ansible.builtin.package:
    name: "{{ php_pkg_spe }}"
    state: present

- name: php_install | Install php*-mysql package
  ansible.builtin.package:
    name: "php{{ php_ver }}-mysql"
    state: present
  when: (nextcloud_db_backend == "mysql") or (nextcloud_db_backend == "mariadb")

- name: php_install | Install php*-pgsql package
  ansible.builtin.package:
    name: "php{{ php_ver }}-pgsql"
    state: present
  when: (nextcloud_db_backend == "pgsql")

- name: php_install | Install PHP APCu pacakge
  ansible.builtin.package:
    name: "php{{ php_ver }}-apcu"
    state: present
