---
- name: tls_installed | Define certificate path
  ansible.builtin.set_fact:
    nextcloud_tls_cert_file: "{{ nextcloud_tls_cert }}"

- name: tls_installed | Define key path
  ansible.builtin.set_fact:
    nextcloud_tls_cert_key_file: "{{ nextcloud_tls_cert_key }}"

- name: tls_installed | Define certificate chain path
  ansible.builtin.set_fact:
    nextcloud_tls_chain_file: "{{ nextcloud_tls_cert_chain }}"
  when: nextcloud_tls_cert_chain is defined
