---
- name: tls_selfsigned | Define private certificate path
  ansible.builtin.set_fact:
    nextcloud_tls_cert_file: "/etc/ssl/{{ nextcloud_instance_name }}.crt"

- name: tls_selfsigned | Define private key path
  ansible.builtin.set_fact:
    nextcloud_tls_cert_key_file: "/etc/ssl/{{ nextcloud_instance_name }}.key"

- name: tls_selfsigned | Create self-signed SSL cert
  ansible.builtin.command: >
    openssl req -new -nodes -x509
    -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${hostname --fqdn}"
    -days 365
    -keyout {{ nextcloud_tls_cert_key_file }}
    -out {{ nextcloud_tls_cert_file }}
    -extensions v3_ca
  args:
    creates: "{{ nextcloud_tls_cert_key_file }}"

- name: tls_selfsigned | Check TLS certificate permissions
  ansible.builtin.file:
    path: "{{ nextcloud_tls_cert_file }}"
    mode: 0644
    group: "{{ nextcloud_websrv_group }}"

- name: tls_selfsigned | Check TLS key permissions
  ansible.builtin.file:
    path: "{{ nextcloud_tls_cert_key_file }}"
    mode: 0640
    group: "{{ nextcloud_websrv_group }}"
