---
- name: websrv_install | Install web server packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ nextcloud_websrv }}"

- name: websrv_install | Install specific Apache web server packages
  ansible.builtin.package:
    name: "libapache2-mod-php{{ php_ver }}"
    state: present
  when: nextcloud_websrv in ["apache2"]
  notify:
    - Start http
    - Reload php-fpm

- name: websrv_install | Install specific NGINX web server packages
  ansible.builtin.package:
    name: "php{{ php_ver }}-fpm"
    state: present
  when: nextcloud_websrv in ["nginx"]
  notify:
    - Start http
    - Reload php-fpm
